import { defineConfig } from "vite";
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import process from "node:process";
import react from "@vitejs/plugin-react";
import tailwindcss from "@tailwindcss/vite";

// When the dev cert is present (generated by scripts/generate-dev-cert.sh),
// the Vite dev server runs over HTTPS so the browser treats it as a secure
// context and the camera/microphone/geolocation permission prompts work —
// even on the LAN IP. Without the cert we fall back to plain HTTP.
const certDir = resolve(process.cwd(), ".dev-certs");
const keyFile = resolve(certDir, "key.pem");
const certFile = resolve(certDir, "cert.pem");
const hasDevCert = existsSync(keyFile) && existsSync(certFile);

if (hasDevCert) {
  console.log(
    "[vite] Dev cert found at .dev-certs/ — serving HTTPS so camera/mic/location permissions work on the LAN IP."
  );
} else {
  console.log(
    "[vite] No .dev-certs/cert.pem found — running plain HTTP.\n" +
      "      Run `npm run dev:https` (or `bash scripts/generate-dev-cert.sh`) to enable\n" +
      "      HTTPS for camera/microphone/location permission prompts."
  );
}

export default defineConfig({
  plugins: [react(), tailwindcss()],
  server: {
    port: 5173,
    host: true,         // listen on 0.0.0.0 + :: — fixes IPv4-only port forwards
    strictPort: true,   // fail fast if 5173 is taken instead of jumping to 5174
    https: hasDevCert
      ? {
          key: keyFile,
          cert: certFile
        }
      : false,
    proxy: {
      "/api": {
        target: "http://localhost:5000",
        changeOrigin: true
      }
    }
  }
});
